spring.application.name=klp-case
spring.threads.virtual.enabled=true

# H2 In-Memory Database
spring.datasource.url=jdbc:h2:mem:klpdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# External API Configuration
county.service.base-url=https://ws.geonorge.no/kommuneinfo/v1